/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/orc20/token-infos': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          ticker?: string
          inscription?: string
          complete?: string
          /** inscription_number,deploy_times,progress,holders,transactions, */
          sort?: string
          deployer?: string
          upgradeable?: string
          tokenId?: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description Brc20 Token 详情上链时间 */
                tokenInfoInscriptionNumberEnd: string
                /** @description Brc20 Token 详情名称 */
                tokenInfoName: string
                /** @description Brc20 Token 详情完成高度完成时间 */
                tokenInfoCompleteBlockTime: string
                /** @description Brc20 Token 详情ID */
                tokenInfoID: string
                /** @description Brc20 Token 详情小数位 */
                tokenInfoTokenDecimal: string
                /** @description Brc20 Token 详情satoshi */
                tokenInfoSatoshi: string
                /** @description Brc20 Token 详情txIdx */
                tokenInfoTxIdx: string
                /** @description Brc20 Token 详情完成高度 */
                tokenInfoCompleteHeight: string
                /** @description Brc20 Token 详情vout */
                tokenInfoVout: string
                /** @description Brc20 Token 详情mint总量 */
                tokenInfoTotalMinted: string
                /** @description Brc20 Token 详情限制数 */
                tokenInfoLimitNumber: string
                /** @description Brc20 Token 详情铭文id */
                tokenInfoInscriptionID: string
                /** @description Brc20 Token 详情createIdxKey */
                tokenInfoCreateIdxKey: string
                /** @description Brc20 Token 详情交易hash */
                tokenInfoTxId: string
                /** @description Brc20 Token 详情ticker */
                tokenInfoTicker: string
                /** @description Brc20 Token 详情最大数 */
                tokenInfoMaxNumber: string
                /** @description Brc20 Token 详情pkScript */
                tokenInfoPkScript: string
                /** @description Brc20 Token 详情铭文number */
                tokenInfoInscriptionNumber: string
                /** @description Brc20 Token 详情部署时间 */
                tokenInfoDeployTimes: string
                /** @description Brc20 Token 详情部署人 */
                tokenInfoDeployer: string
                /** @description Brc20 Token 详情部署高度 */
                tokenInfoDeployHeight: string
                tokenInfoHolders: string
                tokenInfoTransactions: string
                tokenInfoUpgradable: boolean
                tokenInfoProgress: string
                tokenInfoOrc20Id: string
                tokenInfoProtocol: string
                tokenInfoSyncHeight: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/user-token-balances': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          /** 筛选条件 */
          address?: string
          /** 筛选条件 */
          inscriptionNumber?: string
          isDeployer?: string
          sort?: string
          /** true:查询不为0的余额 */
          holder?: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 用户代币余额总余额 */
                userTokenBalanceBalance: string
                /** @description 用户代币余额ticker */
                userTokenBalanceTicker: string
                /** @description 用户代币余额可转账余额 */
                userTokenBalanceTransferableBalance: string
                /** @description 用户代币余额可用余额 */
                userTokenBalanceAvailable: string
                /** @description 用户代币余额地址 */
                userTokenBalanceAddress: string
                /** @description orc20id */
                userTokenBalanceOrc20ID: string
                userTokenBalanceInscriptionNumber: string
                userTokenBalanceLockCredits: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/operation-histories': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          /** 0:非法 1:合法 2:未生效 */
          status?: string
          address?: string
          /**
           * inscribe-deploy
           * inscribe-mint,
           * inscribe-cancel
           * inscribe-send
           * inscribe-upgrade,
           * inscribe-remaining-balance
           * upgrade
           * transfer(receive)
           * send
           *
           * 不传查所有
           */
          method?: string
          inscriptionNumber?: string
          sort?: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 交易历史铭文Number */
                operationHistoryNumber?: string
                /** @description 交易历史fromAddress */
                operationHistoryFromAddress?: string
                /** @description 交易历史高度 */
                operationHistoryHeight?: string
                /** @description 交易历史toAddress */
                operationHistoryToAddress?: string
                /** @description 交易历史铭文id */
                operationHistoryInscriptionID?: string
                /** @description 交易历史类型 */
                operationHistoryType?: string
                /** @description 交易历史Ticker */
                operationHistoryTicker?: string
                /** @description 交易历史数量 */
                operationHistoryAmount?: string
                /** @description 交易历史交易hash */
                operationHistoryTxHash?: string
                /** @description 交易历史pkScriptFrom */
                operationHistoryPkScriptFrom?: string
                /** @description 交易历史satoshi */
                operationHistorySatoshi?: string
                /** @description 交易历史pkScriptTo */
                operationHistoryPkScriptTo?: string
                /** @description 交易历史Vout */
                operationHistoryVout?: string
                /** @description 交易历史块时间 */
                operationHistoryBlockTime?: string
                /** @description 交易历史CreateIdxKey */
                operationHistoryCreateIdxKey?: string
                operationHistoryStatus?: string
                operationHistoryErrorMsg?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/holder-inscribes': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          address: string
          sort?: string
          inscriptionNumber: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 交易历史铭文Number */
                operationHistoryNumber?: string
                /** @description 交易历史fromAddress */
                operationHistoryFromAddress?: string
                /** @description 交易历史高度 */
                operationHistoryHeight?: string
                /** @description 交易历史toAddress */
                operationHistoryToAddress?: string
                /** @description 交易历史铭文id */
                operationHistoryInscriptionID?: string
                /** @description 交易历史类型 */
                operationHistoryType?: string
                /** @description 交易历史Ticker */
                operationHistoryTicker?: string
                /** @description 交易历史数量 */
                operationHistoryAmount?: string
                /** @description 交易历史交易hash */
                operationHistoryTxHash?: string
                /** @description 交易历史pkScriptFrom */
                operationHistoryPkScriptFrom?: string
                /** @description 交易历史satoshi */
                operationHistorySatoshi?: string
                /** @description 交易历史pkScriptTo */
                operationHistoryPkScriptTo?: string
                /** @description 交易历史Vout */
                operationHistoryVout?: string
                /** @description 交易历史块时间 */
                operationHistoryBlockTime?: string
                /** @description 交易历史CreateIdxKey */
                operationHistoryCreateIdxKey?: string
                operationHistoryStatus?: string
                operationHistoryErrorMsg?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/operation-history': {
    get: {
      parameters: {
        query: {
          /** 交易历史ID */
          transfersHistoryID: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 交易历史铭文Number */
              transfersHistoryNumber: string
              /** @description 交易历史名称 */
              transfersHistoryName: string
              /** @description 交易历史fromAddress */
              transfersHistoryFromAddress: string
              /** @description 交易历史高度 */
              transfersHistoryHeight: string
              /** @description 交易历史toAddress */
              transfersHistoryToAddress: string
              /** @description 交易历史铭文id */
              transfersHistoryInscriptionID: string
              /** @description 交易历史类型 */
              transfersHistoryType: string
              /** @description 交易历史Ticker */
              transfersHistoryTicker: string
              /** @description 交易历史数量 */
              transfersHistoryAmount: string
              /** @description 交易历史交易hash */
              transfersHistoryTxHash: string
              /** @description 交易历史pkScriptFrom */
              transfersHistoryPkScriptFrom: string
              /** @description 交易历史satoshi */
              transfersHistorySatoshi: string
              /** @description 交易历史pkScriptTo */
              transfersHistoryPkScriptTo: string
              /** @description 交易历史Vout */
              transfersHistoryVout: string
              /** @description 交易历史块时间 */
              transfersHistoryBlockTime: string
              /** @description 交易历史CreateIdxKey */
              transfersHistoryCreateIdxKey: string
              /** @description 交易历史是否合法 */
              transfersHistoryValid: string
              /** @description 交易历史ID */
              transfersHistoryID: string
              /** @description 交易历史是否使用 */
              transfersHistoryUsed: string
            }
          }
        }
      }
    }
  }
  '/inscribe/file:order': {
    post: {
      parameters: {
        body: {
          /** 请求参数 */
          root?: {
            /** @description 收铭文地址 */
            receiveAddress: string
            /** @description 费率 */
            feeRate: string
            files: { [key: string]: unknown }[]
            satsInInscription: string
            totalAmount: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              orderID: string
              orderOrderNo: string
              orderPayAddress: string
            }
          }
        }
      }
    }
  }
  '/inscribe/order': {
    post: {
      parameters: {
        body: {
          /** 请求参数 */
          root?: {
            /** @description 收铭文地址 */
            receiveAddress: string
            /** @description 费率 */
            feeRate: string
            contentList: number
            satsInInscription: string
            totalAmount: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              orderID: string
              orderOrderNo: string
              orderPayAddress: string
            }
          }
        }
      }
    }
  }
  '/inscribe/inscribe-ranking-list': {
    get: {
      parameters: {
        query: {
          pageNo: number
          pageSize: number
          days?: string
          /** total_fee,row_num */
          sort?: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 订单明细内容 */
                address?: string
                /** @description 订单明细名称 */
                amount?: string
                rank: string
              }[]
            }
          }
        }
      }
    }
  }
  '/inscribe/inscribe-ranking-search': {
    get: {
      parameters: {
        query: {
          address: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              address: string
              amount: string
              weeklyRank: string
              allTimeRank: string
              monthlyRank: string
            }
          }
        }
      }
    }
  }
  '/inscribe/file:dataSize': {
    post: {
      parameters: {
        query: {
          data: string
        }
        body: {
          root?: { [key: string]: unknown }[]
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: number
          }
        }
      }
    }
  }
  '/inscribe/order-details': {
    get: {
      parameters: {
        query: {
          /** 订单明细ID */
          orderId: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 订单明细内容 */
              orderDetailContent: string
              /** @description 订单明细名称 */
              orderDetailName: string
              /** @description 订单明细状态 */
              orderDetailStatus: string
              /** @description 订单明细文件类型 */
              orderDetailContentType: string
              /** @description 订单明细铭文id */
              orderDetailInscriptionId: string
              /** @description 订单明细ID */
              orderDetailID: string
              /** @description 订单明细订单id */
              orderDetailOrderID: string
              /** @description 订单明细铭文号 */
              orderDetailInscriptionNumber: string
              /** @description 订单明细交易id */
              orderDetailTxId: string
              /** @description 订单明细订单号 */
              orderDetailOrdeNo: string
            }[]
          }
        }
      }
    }
  }
  '/inscribe/discount': {
    get: {
      parameters: {
        query: {
          address: string
        }
        body: {
          root?: {
            /** jsonArray */
            data: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              txHash: string
              satPointOnTx: string
              inscriptionId: string
              holder: string
              content: string
              /** @description 折扣 */
              discount: string
            }[]
          }
        }
      }
    }
  }
  '/inscribe/sets-price': {
    get: {
      parameters: {
        body: {
          root?: {
            /** jsonArray */
            jsonArray: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: string
          }
        }
      }
    }
  }
  '/inscribe/orderList': {
    get: {
      parameters: {
        query: {
          /** 订单ID */
          orderIds: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 订单字节大小 */
              orderBytes: string
              /** @description 订单ID */
              orderID: string
              /** @description 订单订单状态 */
              orderOrderStatus: number
              /** @description 订单订单号 */
              orderOrdeNo: string
              /** @description 订单费率 */
              orderFeeRate: number
              /** @description 订单收铭文地址 */
              orderReceiveAddress: string
              /** @description 订单总费用 */
              orderTotalAmount: number
              /** @description 订单服务费 */
              orderServiceFee: string
              /** @description 订单收费地址 */
              orderPayAddress: string
              /** @description 订单支付数量 */
              orderPaidAmount: number
              orderSatsInInscription: string
              orderOrderConfirmed: string
            }[]
          }
        }
      }
    }
  }
  '/inscribe/dataSize': {
    post: {
      parameters: {
        query: {
          data: string
        }
        body: {
          root?: {
            /** jsonArray */
            data: string
          }
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: number
          }
        }
      }
    }
  }
  '/inscribe/orders': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          orderId: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 订单订单状态 */
                orderType?: string
                /** @description 订单字节大小 */
                orderBytes?: string
                /** @description 订单ID */
                orderID?: string
                /** @description 订单订单状态 */
                orderOrderStatus?: string
                /** @description 订单订单号 */
                orderOrdeNo?: string
                /** @description 订单费率 */
                orderFeeRate?: string
                /** @description 订单收铭文地址 */
                orderReceiveAddress?: string
                /** @description 订单总费用 */
                orderTotalAmount?: string
                /** @description 订单服务费 */
                orderServiceFee?: string
                /** @description 订单收费地址 */
                orderPayAddress?: string
                /** @description 订单支付数量 */
                orderPaidAmount?: string
                /** @description 订单是否付费 */
                orderPaid?: string
                /** @description 订单名称 */
                orderName?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/sell-order-details': {
    get: {
      parameters: {
        query: {
          /** 售卖ID */
          sellOrderId: string
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 卖单明细上链时间 */
                sellOrderDetailChainTime?: string
                /** @description 卖单明细地址 */
                sellOrderDetailAddress?: string
                /** @description 卖单明细交易ID */
                sellOrderDetailTxId?: string
                /** @description 卖单明细名称 */
                sellOrderDetailName?: string
                /** @description 卖单明细卖单ID */
                sellOrderDetailSellOrderId?: string
                /** @description 卖单明细状态 */
                sellOrderDetailStatus?: string
                /** @description 卖单明细ID */
                sellOrderDetailID?: string
                /** @description 卖单明细代币数量 */
                sellOrderDetailTokenAmount?: string
                /** @description 售卖ID */
                sellOrderID?: string
                /** @description 卖单明细btc数量 */
                sellOrderDetailBtcAmount?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/sell-orders': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          sellOrderId: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 售卖卖出数量 */
                sellOrderDetailAddress?: string
                /** @description 售卖过期高度 */
                sellOrderDetailTxId?: string
                /** @description 售卖Orc20ID */
                sellOrderDetailStatus?: string
                /** @description 售卖代币名称 */
                sellOrderDetailTokenAmount?: string
                /** @description 售卖状态 */
                sellOrderDetailBtcAmount?: number
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/sell-order-detail': {
    get: {
      parameters: {
        query: {
          /** 售卖ID */
          sellOrderId: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              sellOrderActivationBlock: number
              sellOrderAmount: string
              sellOrderAmountLeft: string
              sellOrderCompleted: string
              sellOrderExpire: string
              sellOrderHasWhiteListed: string
              sellOrderLim: string
              sellOrderPrice: string
              sellOrderProgress: string
              sellOrderSellOrderId: string
              sellOrderSeller: string
              sellOrderSoldAmount?: string
              sellOrderStatus: number
              sellOrderTicker: string
              sellOrderTokenId: string
              sellOrderTokenInscriptionId: string
            }
          }
        }
      }
    }
  }
  '/orc20/sell-order': {
    get: {
      parameters: {
        query: {
          /** 售卖ID */
          sellOrderID: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 售卖卖出数量 */
              sellOrderSoldAmount: string
              /** @description 售卖高度 */
              sellOrderHeight: string
              /** @description 售卖名称 */
              sellOrderName: string
              /** @description 售卖tokenInscriptionId */
              sellOrderTokenInscriptionId: string
              /** @description 售卖买家地址 */
              sellOrderBuyer: string
              /** @description 售卖inscriptionId */
              sellOrderInscriptionId: string
              /** @description 售卖过期高度 */
              sellOrderExpire: string
              /** @description 售卖ID */
              sellOrderID: string
              /** @description 售卖代币ID */
              sellOrderTokenId: string
              /** @description 售卖inscriptionNumber */
              sellOrderInscriptionNumber: string
              /** @description 售卖代币名称 */
              sellOrderTicker: string
              /** @description 售卖状态 */
              sellOrderStatus: string
              /** @description 售卖卖家地址 */
              sellOrderSeller: string
              /** @description 售卖上链时间 */
              sellOrderChainTime: string
              /** @description 售卖单笔购买最大值 */
              sellOrderLim: string
              /** @description 售卖总数 */
              sellOrderAmount: string
              /** @description 售卖单价 */
              sellOrderPrice: string
              /** @description 售卖txID */
              sellOrderTxId: string
            }
          }
        }
      }
    }
  }
  '/orc20/sell-order-white-lists': {
    get: {
      parameters: {
        query: {
          /**
           * 页码
           * 从 1 开始
           * 不传默认为第一页
           */
          pageNo: number
          /**
           * 每页个数
           * 不传默认为 20
           * 最大为 1000
           */
          pageSize: number
          sellOrderId?: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 白名单地址 */
                sellOrderWhiteListAddress?: string
                /** @description 白名单百分比 */
                sellOrderWhiteListPercentage?: string
                /** @description 白名单限额 */
                sellOrderWhiteListLim?: string
                /** @description 白名单已购买数量 */
                sellOrderWhiteListAmountFilled?: string
                /** @description 白名单剩余可购买数量 */
                sellOrderWhiteListAmountLeft?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/sell-order-white-list': {
    get: {
      parameters: {
        query: {
          /** 白名单ID */
          sellOrderWhiteListID: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 白名单地址 */
              sellOrderWhiteListAddress: string
              /** @description 白名单ID */
              sellOrderWhiteListID: string
              /** @description 白名单名称 */
              sellOrderWhiteListName: string
              /** @description 白名单限额 */
              sellOrderWhiteListLim: string
              /** @description 白名单百分比 */
              sellOrderWhiteListAmountaFilled: string
              /** @description 白名单卖单ID */
              sellOrderWhiteListSellOrderId: string
            }
          }
        }
      }
    }
  }
  '/orc20/proposes': {
    get: {
      parameters: {
        query: {
          pageNo: number
          pageSize: number
          ticker?: string
          /** 提议状态1:进行中，2:结束，3:过期 */
          status: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 投票最低数量 */
                quorum?: string
                /** @description 提议状态 */
                status?: string
                /** @description 代币名称 */
                ticker?: string
                /** @description 提议内容 */
                content?: string
                /** @description 提议赞成数量 */
                voteYes?: string
                /** @description 提议通过最低数量 */
                pass?: string
                /** @description 提议反对数量 */
                voteNo?: string
                /** @description 提议版本 */
                proposal?: string
                /** @description 提议投票进度 */
                progress?: string
                /** @description 提议代币ID */
                tokenId?: string
                /** @description 提议上链时间 */
                chainTime?: string
                /** @description 提议代币铭文Id */
                tokenInscriptionId?: string
                /** @description 提议铭文Id */
                inscriptionId?: string
                /** @description 提议赞成代币数量 */
                voteYesAmount?: string
                /** @description 提议反对代币数量 */
                voteNoAmount?: string
                /** @description 提议投票总量 */
                voteAmount?: string
                /** @description 提议结束所需最小投票代币数量 */
                voteQuorumAmount?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/votes': {
    get: {
      parameters: {
        query: {
          pageNo: number
          pageSize: number
          proposeInscriptionId: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 是否还有前一页 */
              hasPrev: boolean
              /** @description 当前页码 */
              pageNo: number
              /** @description 总页数 */
              totalPage: number
              /** @description 每页个数 */
              pageSize: number
              /** @description 是否还有后一页 */
              hasNext: boolean
              /** @description 总数 */
              totalCount: number
              /** @description 数据域 */
              items: {
                /** @description 投票投票代币数量 */
                voteAmount?: string
                /** @description 投票提议版本 */
                voteProposeVersion?: string
                /** @description 投票代币名称 */
                voteTicker?: string
                /** @description 投票投票内容 */
                voteVote?: string
                /** @description 投票提议Id */
                voteProposeId?: string
                /** @description 投票投票信息 */
                voteMsg?: string
                /** @description 投票铭文Id */
                voteInscriptionId?: string
                voteChainTime?: string
                voteAddress?: string
              }[]
            }
          }
        }
      }
    }
  }
  '/orc20/propose': {
    get: {
      parameters: {
        query: {
          /** 提议 ID */
          proposeInscriptionId: string
        }
      }
      responses: {
        /** successful operation */
        200: {
          schema: {
            /**
             * @description 返回消息
             * 异常时返回错误信息
             */
            msg: string
            /**
             * @description 返回码
             * 成功时返回 000 异常时返回码如 105.abm.UNKNOWN
             */
            code: string
            /** @description 返回数据 */
            data: {
              /** @description 提议投票代币比例 */
              proposeQuorum: string
              /** @description 提议提议状态 */
              proposeStatus: string
              /** @description 提议代币名称 */
              proposeTicker: string
              /** @description 提议提议内容 */
              proposeMsg: string
              /** @description 提议当前提议通过比例 */
              proposeRate: string
              /** @description 提议赞成数量 */
              proposeVoteYes: string
              /** @description 提议激活地址 */
              proposeActiveAddress: string
              /** @description 提议过期高度 */
              proposeExpire: string
              /** @description 提议是否激活 */
              proposeIsActived: string
              /** @description 提议提议通过百分比 */
              proposePass: string
              /** @description 提议反对数量 */
              proposeVoteNo: string
              /** @description 提议提议版本 */
              proposeProposeVersion: string
              /** @description 提议铭文ID */
              proposeInscriptionId: string
              /** @description 提议上链时间 */
              proposeChainTime: string
              /** @description 提议结果 */
              proposeResult: string
              /** @description 提议代币Id */
              proposeTokenId: string
              /** @description 提议投票总数 */
              proposeVoteAmount: string
              /** @description 提议结束所需最低投票代币数量 */
              proposeVoteQuorumAmount: string
            }
          }
        }
      }
    }
  }
}

export interface operations {}

export interface external {}

export type Orc20TokenInfosGetParams =
  paths['/orc20/token-infos']['get']['parameters']['query']
export type Orc20TokenInfos =
  paths['/orc20/token-infos']['get']['responses'][200]['schema']['data']
export type Orc20UserTokenBalancesGetParams =
  paths['/orc20/user-token-balances']['get']['parameters']['query']
export type Orc20UserTokenBalances =
  paths['/orc20/user-token-balances']['get']['responses'][200]['schema']['data']
export type Orc20OperationHistoriesGetParams =
  paths['/orc20/operation-histories']['get']['parameters']['query']
export type Orc20OperationHistories =
  paths['/orc20/operation-histories']['get']['responses'][200]['schema']['data']
export type Orc20HolderInscribesGetParams =
  paths['/orc20/holder-inscribes']['get']['parameters']['query']
export type Orc20HolderInscribes =
  paths['/orc20/holder-inscribes']['get']['responses'][200]['schema']['data']
export type Orc20OperationHistoryGetParams =
  paths['/orc20/operation-history']['get']['parameters']['query']
export type Orc20OperationHistory =
  paths['/orc20/operation-history']['get']['responses'][200]['schema']['data']
export type InscribeFileOrderPostParams =
  paths['/inscribe/file:order']['post']['parameters']['body']['root']
export type InscribeFileOrderPost =
  paths['/inscribe/file:order']['post']['responses'][200]['schema']['data']
export type InscribeOrderPostParams =
  paths['/inscribe/order']['post']['parameters']['body']['root']
export type InscribeOrderPost =
  paths['/inscribe/order']['post']['responses'][200]['schema']['data']
export type InscribeInscribeRankingListGetParams =
  paths['/inscribe/inscribe-ranking-list']['get']['parameters']['query']
export type InscribeInscribeRankingList =
  paths['/inscribe/inscribe-ranking-list']['get']['responses'][200]['schema']['data']
export type InscribeInscribeRankingSearchGetParams =
  paths['/inscribe/inscribe-ranking-search']['get']['parameters']['query']
export type InscribeInscribeRankingSearch =
  paths['/inscribe/inscribe-ranking-search']['get']['responses'][200]['schema']['data']
export type InscribeFileDataSizePostParams =
  paths['/inscribe/file:dataSize']['post']['parameters']['body']['root']
export type InscribeFileDataSizePost =
  paths['/inscribe/file:dataSize']['post']['responses'][200]['schema']['data']
export type InscribeOrderDetailsGetParams =
  paths['/inscribe/order-details']['get']['parameters']['query']
export type InscribeOrderDetails =
  paths['/inscribe/order-details']['get']['responses'][200]['schema']['data']
export type InscribeDiscountGetParams =
  paths['/inscribe/discount']['get']['parameters']['query']
export type InscribeDiscount =
  paths['/inscribe/discount']['get']['responses'][200]['schema']['data']
export type InscribeSetsPriceGetParams =
  paths['/inscribe/sets-price']['get']['parameters']
export type InscribeSetsPrice =
  paths['/inscribe/sets-price']['get']['responses'][200]['schema']['data']
export type InscribeOrderListGetParams =
  paths['/inscribe/orderList']['get']['parameters']['query']
export type InscribeOrderList =
  paths['/inscribe/orderList']['get']['responses'][200]['schema']['data']
export type InscribeDataSizePostParams =
  paths['/inscribe/dataSize']['post']['parameters']['body']['root']
export type InscribeDataSizePost =
  paths['/inscribe/dataSize']['post']['responses'][200]['schema']['data']
export type InscribeOrdersGetParams =
  paths['/inscribe/orders']['get']['parameters']['query']
export type InscribeOrders =
  paths['/inscribe/orders']['get']['responses'][200]['schema']['data']
export type Orc20SellOrderDetailsGetParams =
  paths['/orc20/sell-order-details']['get']['parameters']['query']
export type Orc20SellOrderDetails =
  paths['/orc20/sell-order-details']['get']['responses'][200]['schema']['data']
export type Orc20SellOrdersGetParams =
  paths['/orc20/sell-orders']['get']['parameters']['query']
export type Orc20SellOrders =
  paths['/orc20/sell-orders']['get']['responses'][200]['schema']['data']
export type Orc20SellOrderDetailGetParams =
  paths['/orc20/sell-order-detail']['get']['parameters']['query']
export type Orc20SellOrderDetail =
  paths['/orc20/sell-order-detail']['get']['responses'][200]['schema']['data']
export type Orc20SellOrderGetParams =
  paths['/orc20/sell-order']['get']['parameters']['query']
export type Orc20SellOrder =
  paths['/orc20/sell-order']['get']['responses'][200]['schema']['data']
export type Orc20SellOrderWhiteListsGetParams =
  paths['/orc20/sell-order-white-lists']['get']['parameters']['query']
export type Orc20SellOrderWhiteLists =
  paths['/orc20/sell-order-white-lists']['get']['responses'][200]['schema']['data']
export type Orc20SellOrderWhiteListGetParams =
  paths['/orc20/sell-order-white-list']['get']['parameters']['query']
export type Orc20SellOrderWhiteList =
  paths['/orc20/sell-order-white-list']['get']['responses'][200]['schema']['data']
export type Orc20ProposesGetParams =
  paths['/orc20/proposes']['get']['parameters']['query']
export type Orc20Proposes =
  paths['/orc20/proposes']['get']['responses'][200]['schema']['data']
export type Orc20VotesGetParams =
  paths['/orc20/votes']['get']['parameters']['query']
export type Orc20Votes =
  paths['/orc20/votes']['get']['responses'][200]['schema']['data']
export type Orc20ProposeGetParams =
  paths['/orc20/propose']['get']['parameters']['query']
export type Orc20Propose =
  paths['/orc20/propose']['get']['responses'][200]['schema']['data']
