/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
import { Api } from './api'

export class Yapi extends Api {
  get orc20TokenInfos() {
    return this.ft.path('/orc20/token-infos').method('get').create()!
  }

  get orc20UserTokenBalances() {
    return this.ft.path('/orc20/user-token-balances').method('get').create()!
  }

  get orc20OperationHistories() {
    return this.ft.path('/orc20/operation-histories').method('get').create()!
  }

  get orc20HolderInscribes() {
    return this.ft.path('/orc20/holder-inscribes').method('get').create()!
  }

  get orc20OperationHistory() {
    return this.ft.path('/orc20/operation-history').method('get').create()!
  }

  get inscribeFileOrderPost() {
    return this.ft.path('/inscribe/file:order').method('post').create()!
  }

  get inscribeOrderPost() {
    return this.ft.path('/inscribe/order').method('post').create()!
  }

  get inscribeInscribeRankingList() {
    return this.ft
      .path('/inscribe/inscribe-ranking-list')
      .method('get')
      .create()!
  }

  get inscribeInscribeRankingSearch() {
    return this.ft
      .path('/inscribe/inscribe-ranking-search')
      .method('get')
      .create()!
  }

  get inscribeFileDataSizePost() {
    return this.ft.path('/inscribe/file:dataSize').method('post').create()!
  }

  get inscribeOrderDetails() {
    return this.ft.path('/inscribe/order-details').method('get').create()!
  }

  get inscribeDiscount() {
    return this.ft.path('/inscribe/discount').method('get').create()!
  }

  get inscribeSetsPrice() {
    return this.ft.path('/inscribe/sets-price').method('get').create()!
  }

  get inscribeOrderList() {
    return this.ft.path('/inscribe/orderList').method('get').create()!
  }

  get inscribeDataSizePost() {
    return this.ft.path('/inscribe/dataSize').method('post').create()!
  }

  get inscribeOrders() {
    return this.ft.path('/inscribe/orders').method('get').create()!
  }

  get orc20SellOrderDetails() {
    return this.ft.path('/orc20/sell-order-details').method('get').create()!
  }

  get orc20SellOrders() {
    return this.ft.path('/orc20/sell-orders').method('get').create()!
  }

  get orc20SellOrderDetail() {
    return this.ft.path('/orc20/sell-order-detail').method('get').create()!
  }

  get orc20SellOrder() {
    return this.ft.path('/orc20/sell-order').method('get').create()!
  }

  get orc20SellOrderWhiteLists() {
    return this.ft.path('/orc20/sell-order-white-lists').method('get').create()!
  }

  get orc20SellOrderWhiteList() {
    return this.ft.path('/orc20/sell-order-white-list').method('get').create()!
  }

  get orc20Proposes() {
    return this.ft.path('/orc20/proposes').method('get').create()!
  }

  get orc20Votes() {
    return this.ft.path('/orc20/votes').method('get').create()!
  }

  get orc20Propose() {
    return this.ft.path('/orc20/propose').method('get').create()!
  }
}
